class AppStrings {
  static String appName = 'CareLink',
  email = 'Email',
      login = 'Log in',
      username = 'Username',
      password = 'Password',
      forgotPassword = 'Forgot password?',
      signup = 'Sign up',
      signupas = 'Sign up as',
      loginas = 'Login as',
      doctor = 'Doctor',
      patient = 'Patient',
      doctorProfile = 'Doctor Profile',
      uyp = 'Upload your picture',
      drname = 'Doctor name',
      name = 'Name',
      qualification = 'Qualification',
      degree = 'Degree',
      experience = 'Experience',
      yrs = 'Years of experience',
      drId = 'Doctor ID',
      idnumber = 'ID number',
      clinic = 'Clinic Address',
      address = 'Address',
      clicnictime = 'Clinic Timings',
      duration = 'Duration',
      patientprofile = 'Patient Profile',
      patientname = 'Patient name',
      age = 'How old are you',
      fulladdress = 'Full Address',
      gender = 'Gender',
      male = 'Male',
      female = "Female",
      other = 'Other',
      phoneno = 'Phone number',
      forgetpassworddetail1 =
          'Enter the mobile number associated with your account',
      forgetpassworddetail2 =
          'Enter the verfication code sent to your mobile number',
      search = 'Search for Doctor',
      bookappointment = 'Book your Appointment',
      cont = 'Continue',
      details = 'Details',
      timeslot = 'Select Time Slot',
      healthexpert = 'Health Expert',
      resetPasswordInstructions26 = 'Please request a new password reset';
}

class AppCategory {
  static  const body = 'Body',
  ear = 'Ears',
  eye = 'Eyes',
  heart = 'Heart',
  kidney = 'Kidney',
  liver = 'Liver',
  lungs = 'Lungs',
  stomach = 'Stomach',
  tooth = 'Tooth';
}

